name: itch.io upload

on:
  push:
    paths:
      - "version"
      - ".github/workflows/upload-itchio.yml"
      - "export_presets.html.example"

env:
  WORKING_DIRECTORY: docroot

jobs:
  deploy:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Upload to itch.io
        uses: dulvui/itchio-butler-upload@v0.0.1
        with:
          working-directory: docroot
          api-key: ${{ secrets.ITCHIO_API_KEY }}
          user: 4ndrewl
          game: smallworld
          channel: html5
