name: Deploy

on: push
env:
  ITCH_USERNAME: 4ndrewl
  ITCH_GAME_ID: smallworld
jobs:
  deploy:
    name: Upload to Itch
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2.0.8
        with:
          name: 'html5'
          path: build
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./build
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: 'html5'
          buildNumber: ${{ needs.version.outputs.version_hash }}
